db.getCollection('pvs').find({"static.appName":"DX","static.title":{$regex:"UBT"}})
db.getCollection('pvs').find({"static.appName":"NightWatch","static.visitTime":{"$gt":new Date(2017,2,23,14,47,10)}})
db.getCollection('pvs').find({"static.appName":"NightWatch"}).count()
db.getCollection('pvs').find({"business.uid":null})
db.getCollection('pvs').find({"meta.state":""}).count()
db.getCollection('pvs').find({"meta.state":{$exists:true,$ne:"FINISH"},"static.visitTime":{"$lt":new Date(2017,2,15)}}).count()
db.getCollection('pvs').distinct("static.deviceId",{"static.appName":"UBT-Portal"})
db.getCollection('reportresults').find({"reportName":"MR-PrePV","startTime":{"$gt":new Date(2017,2,20)}}).count()
db.getCollection('reportresults').find({"reportName":{$regex:"Agg-static.userAgent"}}).count()
db.getCollection('reportresults').find({})
db.getCollection('configs').find({})